### ISSUE TITLE
Fix : close joystick and gamecontroller

### ISSUE THREAD

**Issue by BeWorld2018** [pr-starfighter/starfighter#11]
On engine.c line 495, please add this to close joystick/gamecontroller 
Thanks for this implementation

```

	// Close controllers
	for (i=0; i<SDL_NumJoysticks(); i++) {
		if (engine.useController)
			SDL_GameControllerClose(i);
		else
			SDL_JoystickClose(i);
	}

```

**Comment by onpon4** [comment]
Could you open pull requests for this kind of thing rather than issues, please (or at least direct me to a Git repo where you've made the changes)? It's a lot easier to merge a PR than to manually insert code myself.

Also, can I ask what the reason for this is? Does not doing this cause a memory leak somewhere? Asking because AddressSanitizer doesn't report any possible memory leaks and the SDL documentation doesn't tell you that you have to close joysticks and gamepads.

🕵️

**Comment by BeWorld2018** [comment]
Sorry, i will try next time.

I think it's better to close all for a better compatibility...
When i quit game, i have some crash, so i test all close
I doesnt see Mix_Quit();

I contniue to search why... (so you can close this issue)

**Comment by onpon4** [comment]
You say the game is crashing when you quit? Are you getting some kind of error or segfault?

I don't think the lack of "quit"s would be the cause of that, but if it's a segfault, you may wish to compile with `./configure DFLAGS="-fsanitize=address"` (assuming you have a recent enough version of GCC to use AddressSanitizer). It comes up clean on my end, but let me know if you encounter any errors..

🕵️

**Comment by BeWorld2018** [comment]
hi !
Ok i find why crash and it's not close function :-)
I find a bug on SDL2_image on MorphOS. I fix that.

So i test without close joystick unless close and working.. so you can close.
