### ISSUE TITLE
Compilation Error: `gcc: error: unrecognized command line option ‘-Wformat-truncation=0’`

### ISSUE THREAD

**Issue by abetusk** [pr-starfighter/starfighter#18]
When trying to compile from source, I get the following error:

```
gcc: error: unrecognized command line option ‘-Wformat-truncation=0’
```

Going through and removing the `-Wformat-truncation=0` from the Makefile in both the root and `src` directory looks to "fix" the issue and I'm able to compile and play the game.

Here is some information about my system:

```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
```

**Comment by onpon4** [comment]
It's because you're using too old a version of GCC. GCC 8 introduced warnings about possible truncation that get included in -Wall, so we added -Wformat-truncation=0 to avoid a bunch of meaningless errors, but of course, older versions of GCC don't recognize the option. You can use older versions of GCC by setting the SF_NOWARN environment variable, for example:

`./configure SF_NOWARN=1`

This is actually done to build the Windows binaries because MXE (which we use to cross-compile) also has an old GCC version.

🕵️

**Comment by onpon4** [comment]
I'm tagging this with the documentation label because it's been asked by a few people now. I'll need to figure out a way to keep the benefits of our current setup without confusing end-users.

🕵️

**Comment by onpon4** [comment]
I've pushed a change so that warnings are now disabled by default and enabled with the SF_WARN option instead of disabled by SF_NOWARN. This should prevent this issue and also ensure compatibility with compilers other than GCC.

🕵️
